dsfr/templates/dsfr/form_field_snippets/input_snippet.html, example_app/forms.py, example_app/urls.py
Ajouter la classe fr-input directement avec widget_tweaks pose des effets de bord parce que cela dépend en fait du type de champ.
Gestion des formulaires d'exemple avec  DsfrBaseForm à la place
=> Utilisation de DsfrBaseForm pour les formulaires d'exemple

example_app/templates/example_app/blocks/footer.html
Le bouton de la modale est décalé sur le site d’exemple par rapport au reste de la ligne, parce qu'il utilise une classe obsolète.
=> Réparer le bouton de la modale

dsfr/templates/dsfr/form_field_snippets/input_snippet.html
Fix du template input_snippet.html qui produit un <label> dans un <label>
Exemple de code généré avec `{% dsfr_form %}` :
```
<label for="id_reason" class="fr-label">
<label for="id_reason">Pourquoi séparer cette carte du compte&nbsp;?</label>
</label>
=> Fix du template input_snippet.html qui produit un <label> dans un <label>

dsfr/static/css/dsfr-django-overrides.css, dsfr/templates/django/forms/errors/dict/ul.html, dsfr/templates/django/forms/errors/list/ul.html, dsfr/templates/dsfr/form_field_snippets/checkbox_snippet.html, dsfr/templates/dsfr/form_field_snippets/checkboxselectmultiple_snippet.html, dsfr/templates/dsfr/form_field_snippets/input_snippet.html, dsfr/templates/dsfr/form_field_snippets/radioselect_snippet.html, dsfr/templates/dsfr/form_snippet.html, dsfr/templates/dsfr/global_css.html
Design plus intégré du rendu des erreurs Django. Cette PR rajoute le fichier `dsfr/static/css/dsfr-django-overrides.css`. Il y a peut-être de la doc à modifier ?
- Meilleure intégration du DSFR dans les erreurs Django
- Affichage des erreurs générales lors de l'utilisation de `{% dsfr_form %}`
=> Design plus intégré du rendu des erreurs Django

dsfr/static/js/formsets.js, dsfr/templates/dsfr/formset_base.html, example_app/views.py
Bugfix
Il y avait des problèmes avec les formsets :
-Lorsqu'il y a plusieurs forms dans un formset, seul le premier s'enregistrait
-Lorsqu'on supprime un des forms, ça buggait
J'ai modifié le fichier formsets.js pour corriger cela.
-Pour ajouter un form dans le formset, il faut que l'id des champs soit de la forme "{nom de l'objet}_set-{numéro du formset}-{nom du champ}". Donc il faut passer au contexte le nom de l'objet concerné par le formset. Du coup dans views.py, j'ai ajouté : context["object_name"] = "book"
-Au lieu de supprimer la case "supprimer" créée automatiquement par Django, je la cache. Lors de la suppression d'un form, la case est cochée et le form est caché au lieu d'être supprimé.
=> Fix formsets

dsfr/forms.py, example/settings.py
Utilisation d'un moteur de rendu de template custom sur la classe `DsfrDjangoTemplates`
Cette modification permet de se passer de modifier les paramètres `FORM_RENDERER` et `TEMPLATES.DIRS` dans le `settings.py` et de limiter l'utilisation des templates dans `dsfr/templates/django/forms/widgets` aux formulaires rendus avec la classe `DsfrBaseForm`.
Nous avons actuellement ce besoin sur [betagouv/Aidants_Connect](https://github.com/betagouv/Aidants_Connect) puisqu'une partie du site est en DSFR et une partie est sur un ancien design. Les templates dans `dsfr/templates/django/forms/widgets` cassent une partie des pages qui sont sur l'ancien design.
Je n'ai pas trouvé où modifier la documentation.
=> Utilisation d'un moteur de rendu de template custom sur la classe `DsfrDjangoTemplates`

dsfr/templates/dsfr/alert.html, dsfr/templatetags/dsfr_tags.py, example_app/tag_specifics.py, example_app/views.py
Ajout d'une balise pour rendre les messages Django. Cette PR rend aussi le titre de notification de la balise `dsfr_alert` optionnel.
Rendu :
=> Ajout d'une balise pour rendre les messages Django

INSTALL.md, dsfr/forms.py, example/settings.py
Si `settings.FORM_RENDERER != global_settings.FORM_RENDERER`, la propriété ne retourne rien. Cette PR résout ce problème.
=> Petit fix sur le default_renderer de DsfrBaseForm et màj de la documentation

example_app/tag_specifics.py, example_app/templates/example_app/page_tag.html, example_app/views.py
- Documentation du tag `django_messages`
- L'outil de formatage de DJLint déconne au niveau des lignes 49-55 de `page_tag.html`, j'ai dû ajouter des balises `djlint:off` et `on` (pour qu'il ne décale pas le reste du fichier) sauvegarder sans formater et commit en `--no-verifiy`. Cela correspond *a priori* au ticket https://github.com/Riverside-Healthcare/djLint/issues/769
=> Documentation du tag django_messages

dsfr/forms.py, dsfr/templates/dsfr/form_field_snippets/checkbox_snippet.html, dsfr/templates/dsfr/form_field_snippets/checkboxselectmultiple_snippet.html, dsfr/templates/dsfr/form_field_snippets/input_snippet.html, dsfr/templates/dsfr/form_field_snippets/radioselect_snippet.html, dsfr/templatetags/dsfr_tags.py, dsfr/utils.py
`dsfr_form_field` est inutile s'il n'est pas utilisé avec `DsfrBaseForm` puisque la classe CSS est paramétrée dans `DsfrBaseForm`. C'est la seule chose qui est configurée au niveau du formulaire et pas au niveau template, ce qui est contre-intuitif.
Cette PR ajoute cette logique dans un filtre à utilisé sur chaque `field`.
=> Configuration des classes CSS dans le template en même temps que dans le Form

dsfr/constants.py, dsfr/templates/dsfr/base.html, dsfr/templatetags/dsfr_tags.py, dsfr/utils.py, example_app/forms.py, example_app/templates/example_app/blocks/header.html, example_app/templates/example_app/page_colors.html, example_app/urls.py, example_app/views.py, pyproject.toml
Certains composants ont des options de couleur d’accentuation permettant de créer des thèmes. Ajout d'une page d'exemple.
=> Ajoute une page pour montrer la gestion des couleurs

Makefile, example_app/dsfr_components.py, example_app/management/commands/import_sample_data.py, example_app/templates/example_app/components_index.html, example_app/templates/example_app/page_component.html, example_app/templates/example_app/page_icons.html, example_app/templates/example_app/page_pictograms.html, example_app/views.py
Il faudrait, d'une part, pointer vers le site d'exemples officiel (https://main--ds-gouv.netlify.app/example/) et d'autre part, améliorer l'accessibilité de certaines pages d'exemple
=> Amélioration de la documentation

INSTALL.md
Corrige l'issue #118
Il manque une virgule pour séparer `"widget_tweaks"` et `"dsfr"`.
C'est un bugfix qui évite l'erreur
`ModuleNotFoundError: No module named 'widget_tweaksdsfr'`
=> fix(INSTALL.md): typo in INSTALLED_APPS

dsfr/templates/dsfr/form_field_snippets/checkbox_snippet.html, dsfr/utils.py
Comme signalé dans #124, les libellés des cases à cocher simples sont terminées par un ":" alors que la case est avant le libellé.
Après vérification de la documentation du DSFR, aucun libellé de champ de formulaire ne devrait avoir de ":", je vais donc également les retirer sur les cases à cocher multiples (les autres champs n'ont déjà pas ce suffixe)
=> Retrait des ":" dans les libellés de champ.

dsfr/context_processors.py, dsfr/templates/dsfr/base.html, example_app/templates/example_app/blocks/header.html, example_app/templates/example_app/index.html
Permettre de configurer le fil d'Ariane sur le template d'une page donnée.
_(optionnel) Documentation, commandes à lancer, variables d’environnement, etc._
=> Ajout d'un bloc breadcrumb au template base.html

doc/forms.md, dsfr/templatetags/dsfr_tags.py, dsfr/test/test_templatetags.py
Nouvelle fonctionnalité : ajoute la possibilité d'utiliser un autre formulaire que le `form` présent dans le contexte.
=> Ajoute la possibilité d'utiliser un autre formulaire que le `form` présent dans le contexte

dsfr/templates/dsfr/header.html, dsfr/templatetags/dsfr_tags.py, example_app/dsfr_components.py, poetry.lock, pyproject.toml
L'identifiant par défaut du menu principal mobile est incohérent, mise en cohérence
=> Bug menu mobile

dsfr/templates/dsfr/form_field_snippets/field_snippet.html
Utile pour faire :
```python
{% for field in form %}
{% dsfr_form_field field %}
{% endfor %}
=> Pris en charge du rendu des champs cachés.

dsfr/templates/dsfr/footer.html
Permet d'ajouter du texte juste apres la déclaration de licence etalab 2.0 , dans le footer
=> add custom footer license block

example_app/dsfr_components.py, example_app/forms.py, example_app/templates/example_app/page_colors.html, example_app/views.py
Il est possible de changer la couleur de fond d’un paragraphe, mais cela est mal documenté sur le site du DSFR.
=> [Documentation] Ajout d’un exemple montrant comment faire un paragraphe avec une couleur de fond alternative

dsfr/templates/dsfr/form_field_snippets/checkboxselectmultiple_snippet.html, example_app/forms.py
Correction de la checkbox multiple de démo qui ne marche pas, et de l'affichage des erreurs liées
=> [Bugfix] Correction de l’affichage des erreurs pour les checkbox multiples

doc/forms.md, dsfr/enums.py, dsfr/templates/dsfr/widgets/rich_radio.html, dsfr/templates/dsfr/widgets/rich_radio_option.html, dsfr/test/test_enums.py, dsfr/utils.py, dsfr/widgets.py, example_app/forms.py, example_app/utils.py
Voici ma tentative d'ajouter des boutons radio riches. Je suis un peu sceptique sur cette solution parce qu'elle repose sur une nouvelle forme d'`enum`s, plus complexe et qui repose pas mal sur la métaprogrammation, ce qui peut être difficile à maintenir. Mais pour l'instant, c'est la solution la plus user-friendly que j'ai trouvée. L'idée, c'est de l'utiliser comme ça :
```python
from django import forms
from dsfr.forms import DsfrBaseForm
from dsfr.widgets import RichRadioButtonWidget
from django.utils.safestring import mark_safe
class ComplexChoices(RichRadioButtonChoices):
ITEM_1 = {
"value": "Item_1",
"label": "Item 1",
"pictogram": "/static/images/item1.png",
"html_label": mark_safe("<span>Item 1</span>"),
}
ITEM_2 = {
"value": "Item_2",
"label": "Item 2",
"pictogram": …
```
=> Ajout des boutons radio riches

dsfr/templates/dsfr/form_field_snippets/input_snippet.html, example_app/forms.py, pyproject.toml
Le texte d’aide d’un champ de formulaire doit pouvoir contenir des liens ou de la mise en forme si besoin. Actuellement, il est rendu en texte brut.
=> [Formulaires] Autoriser le HTML dans le texte d’aide des champs de formulaire

dsfr/templates/dsfr/form_field_snippets/checkbox_snippet.html, dsfr/templates/dsfr/form_field_snippets/checkboxselectmultiple_snippet.html, dsfr/templates/dsfr/form_field_snippets/radioselect_snippet.html, pyproject.toml
Le texte d’aide d’un champ de formulaire doit pouvoir contenir des liens ou de la mise en forme si besoin. Actuellement, il est rendu en texte brut.
(Même chose que #183 mais pour les autres types de champ)
=> [Formulaires] Autoriser le HTML dans le texte d’aide de tous les types de champs de formulaire

dsfr/templates/dsfr/alert.html, dsfr/templatetags/dsfr_tags.py, dsfr/test/test_templatetags.py
Ça permet d'utiliser de contrôler le bouton avec des framework JS comme HTMX ou Stimulus.
=> Ajoute la possibilité de paramétrer les attributs HTML du bouton de clôture de l'alerte

dsfr/enums.py, dsfr/templates/dsfr/form_field_snippets/checkbox_snippet.html, dsfr/templates/dsfr/form_field_snippets/checkboxselectmultiple_snippet.html, dsfr/templates/dsfr/form_field_snippets/input_snippet.html, dsfr/templates/dsfr/form_field_snippets/radioselect_snippet.html, dsfr/templatetags/dsfr_tags.py, dsfr/test/test_enums.py, dsfr/utils.py, example_app/forms.py, example_app/tests.py
- Simplification des templates de `form_field_snippets` en définissant `aria-describedby` dans le filtre `dsfr_input_class_attr`
- Remplacement de `field.label_tag` par `field.label` lorsque `<label>` ou `<legend>` sont explicitement utilisés dans le template (ça provoquait l'imbrication d'un `<label>` dans un  `<label>` ou `<legend>`)
- Prise en charge des cases à cocher et des boutons radio inline
- Ajout de la possibilité de définir des champs inline avec le nouveau filtre `dsfr_inline`.
- Réécriture de `checkboxselectmultiple_snippet.html` et `radioselect_snippet.html` pour être cohérent avec la documentation DSFR.
=> Multiple corrections sur le DSFR

.github/workflows/ci-3-10.yml, poetry.lock, pyproject.toml
```
- Updating cryptography (43.0.1 -> 43.0.3)
- Updating six (1.16.0 -> 1.17.0)
- Updating nh3 (0.2.18 -> 0.2.19)
- Updating sqlparse (0.5.1 -> 0.5.3)
- Updating django (4.2.16 -> 4.2.17)
- Updating json5 (0.9.25 -> 0.10.0)
- Updating keyring (25.4.1 -> 25.5.0)
- Updating packaging (24.1 -> 24.2)
- Updating regex (2024.9.11 -> 2024.11.6)
- Updating rich (13.9.2 -> 13.9.4)
- Updating tqdm (4.66.5 -> 4.67.1)
- Updating virtualenv (20.26.6 -> 20.28.0)
```
=> Mise à jour des dépendances Python et de la CI

dsfr/test/test_forms.py, dsfr/utils.py
L'usage de `dsfr_input_class_attr` provoque une validation inattendue du formulaire dans `DsfrBaseForm.__init__`
=> Correction de régression sur `dsfr_input_class_attr`

pyproject.toml
Ajout d’une ligne manquante nécessaire pour la publication du paquet sur Pypi
=> Correction pyproject.toml pour build/publish

poetry.lock
```
- Updating cssbeautifier (1.15.1 -> 1.15.3)
- Updating django (5.1.5 -> 5.1.6)
- Updating identify (2.6.6 -> 2.6.8)
- Updating stevedore (5.4.0 -> 5.4.1)
- Installing typing-extensions (4.12.2)
- Updating virtualenv (20.29.1 -> 20.29.2)
- Updating bandit (1.8.2 -> 1.8.3)
- Updating beautifulsoup4 (4.12.3 -> 4.13.3)
- Updating lxml (5.3.0 -> 5.3.1)
```
=> Mise à jour des dépendances Python

doc/follow.md, example_app/management/commands/import_sample_data.py, example_app/templates/example_app/base.html
Alternative à #207 : Suite à un audit de numerique.gouv un problème a été remonté, le block newsletter de Sites-Faciles n'est ni dans la balise <main> ni dans la balise <footer>. Une suggestion a été de le mettre dans un `<aside>` : 
> ÀMHA ce bloc répété, complémentaire du contenu principal, est à identifier en tant que tel -> aside (role="complementary")
sinon dans un élément navigation.
le footer (role="contentinfo") est normalement réservé à des métadonnées : de l’information à propos du contenu.
La newsletter n’est pas de l’information à propos du contenu (comme les mentions légales ou la déclaration d’accessibilité), c’est un contenu en soi du site.
_(optionnel) Documentation, commandes à lancer, variables d’environnement, etc._
- _(optionnel) Une liste d’autres modifications pas en …
=> Lettre d’information et réseaux sociaux : Ajout d’un aside autour du bloc dans la documentation

dsfr/templatetags/dsfr_tags.py, pyproject.toml
Dans sa version actuelle, le templatetag `dsfr_css` passe une variable inutile dans le contexte de son template, et oublie par contre une variable qui serait utile.
La conséquence est que dans le rendu HTML, le hash d'intégrité d'un fichier CSS est vide. C'est un problème mineur car les navigateurs ignorent les hashs vides, mais ce sera plus propre avec cette PR.
- Juste remplacer la variable inutile par la variable requise
=> Correction d'un hash d'intégrité vide pour un fichier CSS

doc/header.md, dsfr/templates/dsfr/header.html, example_app/templates/example_app/blocks/header.html, pyproject.toml
Dans le header il peut y avoir des `<ul>` vide s'il n'y a pas de contenue. 
Mettre la liste à l'intérieur du bloc
D'après ce que j'ai pu voir c'est au niveau du select du thème. Sur Wgtail si on choisit de ne pas afficher le select il reste une balise vide.
@Ash-Crow je n'ai pas en tête si ça peut avoir des incidences sur des projets qui utilisent Django DSFR.
=> Prévient les listes vides

doc/forms.md
_Un résumé de l’objectif de la PR_
Correction minime dans la documentation des formulaires
- Dans le paragraphe "Classes CSS", l'exemple de champ PasswordInput avait une erreur
=> fix PasswordInput doc

dsfr/templates/dsfr/form_field_snippets/field_snippet.html, dsfr/test/test_form_field_snippets.py, dsfr/widgets.py, example_app/forms.py
Corrige #154 , en rendant possible l'affichage inline des boutons radio au sein d'un formulaire.
C'était juste un petit bug : tout était prévu, sauf que l'attribut `inline`, en tant qu'attribut custom du widget, soit accessible au sein du formulaire via `.attrs.inline` plutôt que `.inline`.
J'ai donc créé un petit test qui mettait le bug en lumière, et qui est maintenant au vert, grâce au simple ajout de `.attrs`.
Apparemment j'ai inauguré le fait d'écrire des tests sur les snippets de widget de formulaire, je ne sais pas si je m'y suis pris de la bonne manière, donc peut-être point d'attention particulier là-dessus pendant la relecture.
=> [FIX] Corriger le rendu de bouton radio inline

dsfr/templatetags/dsfr_tags.py, dsfr/test/test_templatetags.py
Cette PR corrige un bug sur `dsfr_tile`, our lequel la surcharge de `heading_tag` a été oubliée dans les paramètres autorisés.
- Un test passant pour couvrir le fonctionnement nominal de `dsfr_tile`
- Un test pour mettre en lumière le bug
- Le correctif du bug qui consiste à juste ajouter la clé `heading_tag` aux clés autorisées
=> Autoriser la surcharge du heading_tag de dsfr_tile

dsfr/fields.py, dsfr/templates/dsfr/form_field_snippets/field_snippet.html, dsfr/templates/dsfr/form_field_snippets/input_snippet.html, dsfr/templates/dsfr/form_field_snippets/numbercursor_snippet.html, dsfr/templates/dsfr/widgets/number_cursor.html, dsfr/test/test_fields.py, dsfr/widgets.py, example_app/forms.py, example_app/tests.py
Intégrer le champ de formulaire [Curseur](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/curseur-range/) aux widgets possibles pour les champs de formulaire.
Closes #129 
- Ajout d'un snippet dédié pour pouvoir afficher les bornes inférieures/supérieures automatiquement dans le texte d'aide
- Ajout du widget en lui-même, qui gère les bornes inférieures/supérieures, les crans si besoin, le faire d'être simple ou double, et évidemment un `extra_classes` pour la petite taille
- Ajout d'un nouveau champ Django pour le cas du curseur double qui permet de choisir un intervalle de valeurs ; ce champ retournant un `range` Python
- Suppression du load `widget_tweaks` là où il n'était pas nécessaire dans `input_snippet.html`
=> Ajouter les curseurs dans les formulaires

dsfr/templates/dsfr/tooltip.html, dsfr/test/test_templatetags.py
Dans sa version actuelle, le composant Tooltip avec l'option `is_clickable`, est considéré comme un `<button type="submit">`, ce qui le rend considéré par les `<form>` comme un bouton de validation, quand l'utilisateur appuie sur `[Entrée]` dans un champ texte par exemple.
Cette PR ajoute simplement le `type="button"` pour que ce bouton soit considéré comme un simple bouton d'action locale.
De manière similaire à #213
=> [FIX] Le composant Tooltip, quand cliquable, doit avoir type="button"

dsfr/templatetags/dsfr_tags.py
L'issue décrit le problème: https://github.com/numerique-gouv/django-dsfr/issues/232
L'objectif est d'avoir dans la vue debug de la template l'origine exacte de l'erreur quand avec le tag `dsfr_form_field` on ne met pas le bon champs.
Un test au niveau du tag `dsfr_form_field` pour éviter que les typos dans les noms de champs fassent des erreurs très difficiles à remonter
On pourrait même tester le type  de variable pour s'assurer que c'est bien un champs de formulaire.
Je n'ai pas encore écrit les tests.
Maintenant on sait ou regarder si le champs n'est pas bien nommé au niveau de la template
=> Affichage des erreurs de champs

dsfr/templatetags/dsfr_tags.py, dsfr/test/test_fields.py, dsfr/utils.py
Fix #232
Permet un meilleur message d’erreur quand un champ inexistant est appelé. Malheureusement, le nom du champ est inaccessible à ce stade, s'il n’existe pas c'est une chaîne vide qui est passée au lieu d’un `BoundField` : impossible de donner le nom du champ en erreur dans le message d’erreur
=> Ajout d‘une vérification si un champ existe dans dsfr_input_class_attr()

doc/forms.md, dsfr/enums.py, dsfr/templates/dsfr/form_field_snippets/field_snippet.html, dsfr/templates/dsfr/form_field_snippets/segmented_control_snippet.html, dsfr/templates/dsfr/widgets/segmented_control.html, dsfr/templates/dsfr/widgets/segmented_control_option.html, dsfr/test/test_form_field_snippets.py, dsfr/widgets.py, example_app/dsfr_components.py, example_app/forms.py
Implémente [le contrôle segmenté](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/controle-segmente/) en tant que champ de formulaire Django.
Closes #128 
- Ajout d'un nouveau widget qui gère l'affichage des options ainsi que les différentes variantes (petit, légende inline)
- S'appuie sur les `ExtendedChoices` pour permettre l'ajout d'un icône à chaque option
- Juste le renommage d'une classe dont le nom ne reflétait pas son niveau de généricité
- Je me suis aussi permis, dans le dernier commit, de mettre à jour la liste des composants pas encore implémentés, qui est maintenant vide :tada: 
Les trois variantes : classique, légende inline, pas de légende visible (la dernière est également en petite taille)
=> Champ de formulaire pour les contrôles segmentés

dsfr/templates/dsfr/theme_modale.html, dsfr/templates/dsfr/transcription.html, dsfr/test/test_templatetags.py, example_app/templates/example_app/example_consent_modale.html, example_app/test/test_views.py
Les modales ont actuellement une arborescence des titres séparées de la principale, conformément à ce qui est recommandé dans https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/modale/
Cependant, cela pose problème avec des outils d'analyse mal conçus qui ne séparent pas les arborescences. Par exemple https://www.webrankinfo.com/outils/balises-h1-h6.php affiche
```
..<h1> Créez un site en autonomie
....<h2> Vous êtes agent de l’État ? Publiez un site internet ou intranet conforme au DSFR, sans coder ni peser sur votre budget.
....<h2> Trois bonnes raisons d'utiliser Sites Faciles
......<h3> Créez un site conforme
......<h3> Travaillez en autonomie
[...]
....<h2> La feuille de route de Sites Faciles Étape 3 sur 4
....<h2> Améliorons Sites Faciles ensemble
....<h2> …
```
=> Remplacer h1 par h2 dans les modales

.github/ISSUE_TEMPLATE/1-bug.md, .github/ISSUE_TEMPLATE/2-suggestion.md, .github/ISSUE_TEMPLATE/3-doc.md, .github/ISSUE_TEMPLATE/config.yml
Ajout de [modèles d'issues pour Github](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser), similaires au modèle de PR déjà existant et inspirés de [ceux du DSFR](https://github.com/GouvernementFR/dsfr/tree/main/.github/ISSUE_TEMPLATE).
=> Ajout de modèles d'issue Github

Makefile, doc/usage.md, dsfr/templates/dsfr/global_css.html, dsfr/templates/dsfr/global_js.html, dsfr/templatetags/dsfr_tags.py, dsfr/test/test_templatetags.py, pyproject.toml
Rend les checksums d'intégrité optionnels. Tentative pour résoudre #226 
_(optionnel) Documentation, commandes à lancer, variables d’environnement, etc._
_(optionnel) Une ou plusieurs captures d’écran, si pertinent_
=> Integrity checks optional
